//
//  Copyright © 2025 SHEEN TECH LAB. All Rights Reserved.
//
//! @file SlateCefSettings.h
//! @brief Declares the FSlateCefSettings structure
#pragma once

#pragma region <Engine Headers>
// Core/Public/
#include <Containers/UnrealString.h>
#include <HAL/Platform.h>
// CoreUObject/Public/
#include <UObject/ObjectMacros.h>
#pragma endregion

#pragma region <Project Public Headers>
#include <CefViewTypes.h>
#pragma endregion

/// <summary>
/// Represents the log severity for CEF logging output.
/// Controls the verbosity of log messages generated by the Chromium Embedded Framework.
/// </summary>
enum class ESlateCefLogLevel : uint8
{
  /// <summary>
  /// Default logging level (currently INFO logging).
  /// Use this to inherit the default logging behavior of CEF.
  /// </summary>
  Default,

  /// <summary>
  /// Enables verbose logging, providing the most detailed log output.
  /// Useful for in-depth debugging and development.
  /// </summary>
  Verbose,

  /// <summary>
  /// Enables DEBUG level logging.
  /// Provides detailed information for diagnosing issues.
  /// </summary>
  Debug,

  /// <summary>
  /// Enables INFO level logging.
  /// Provides informational messages about normal application operation.
  /// </summary>
  Info,

  /// <summary>
  /// Enables WARNING level logging.
  /// Logs potentially harmful situations that are not necessarily errors.
  /// </summary>
  Warning,

  /// <summary>
  /// Enables ERROR level logging.
  /// Logs error events that might still allow the application to continue running.
  /// </summary>
  Error,

  /// <summary>
  /// Enables FATAL level logging.
  /// Logs very severe error events that will presumably lead the application to abort.
  /// </summary>
  Fatal,

  /// <summary>
  /// Disables logging to file for all messages, and to stderr for messages with severity less than FATAL.
  /// Use this to suppress most log output.
  /// </summary>
  Disable = 99
};

/// <summary>
/// Represents the settings for a single CefView instance.
/// Configure this struct to control CEF behavior, resource mapping, localization, logging, and debugging.
/// </summary>
struct UCEFVIEW_API FSlateCefSettings
{
  /// <summary>
  /// The name of the bridge object injected into all browser frames.
  /// This object enables communication between JavaScript in web content and native C++ code.
  /// It is accessible in JavaScript as a property of the window object (e.g., window.bridgeObject).
  /// Default: "UCefViewBridge"
  /// </summary>
  FName BridgeObjectName = TEXT("UCefViewBridge");

  /// <summary>
  /// The name of the built-in custom URL scheme used for resource mapping and internal communication.
  /// Default: "UCefView"
  /// </summary>
  FName BuiltinSchemeName = TEXT("UCefView");

  /// <summary>
  /// The user agent string to be used by the browser.
  /// If empty, the default CEF user agent will be used.
  /// </summary>
  FString UserAgent;

  /// <summary>
  /// List of archive file resource mappings (only .zip format is supported).
  /// Each mapping specifies a virtual URL and a corresponding archive file path (relative to the Game Dir).
  /// Resources inside the archive can be accessed via the mapped URL.
  /// </summary>
  TArray<FArchiveFileResourceMapping> ArchiveFileResourceMapping;

  /// <summary>
  /// List of local folder resource mappings.
  /// Each mapping specifies a virtual URL and a corresponding folder path (relative to the Game Content Dir).
  /// Resources inside the folder can be accessed via the mapped URL.
  /// </summary>
  TArray<FLocalFolderResourceMapping> LocalFolderResourceMapping;

  /// <summary>
  /// The background color used for the browser view.
  /// This color is used when no web content is loaded or as the default background.
  /// Default: FColor::White
  /// </summary>
  FColor BackgroundColor = FColor::White;

  /// <summary>
  /// The locale to use for browser UI and web content.
  /// If empty, the default locale "en-US" is used.
  /// On Linux, this value is ignored and locale is determined from environment variables (LANGUAGE, LC_ALL,
  /// LC_MESSAGES, LANG). Can also be set using the "lang" command-line switch.
  /// </summary>
  FString Locale;

  /// <summary>
  /// Comma-delimited, ordered list of language codes (without whitespace) to use in the "Accept-Language" HTTP header.
  /// Determines the preferred languages for web content.
  /// Example: ["en-US", "fr", "de"]
  /// </summary>
  TArray<FString> AcceptLanguageList;

  /// <summary>
  /// Whether to persist session cookies across browser restarts.
  /// If true, session cookies are saved and restored; if false, they are cleared on shutdown.
  /// Default: true
  /// </summary>
  bool PersistSessionCookies = true;

  /// <summary>
  /// Whether to persist user preferences (such as autofill data, settings, etc.).
  /// If true, preferences are saved and restored; if false, they are reset on shutdown.
  /// Default: true
  /// </summary>
  bool PersistUserPreferences = true;

  /// <summary>
  /// The log level for CEF logging output.
  /// Controls the verbosity of log messages written by CEF.
  /// Default: ESlateCefLogLevel::Default
  /// </summary>
  ESlateCefLogLevel LogLevel = ESlateCefLogLevel::Default;

  /// <summary>
  /// The port number to enable remote debugging with Chrome DevTools.
  /// If set to a value greater than zero, remote debugging is enabled and you can connect using Chrome/Edge.
  /// Default: 0 (disabled)
  /// </summary>
  int32 RemoteDebuggingPort = 0;

  /// <summary>
  /// Whether to disable passing the application command line arguments to CEF.
  /// If true, only explicitly specified command line arguments are passed to CEF.
  /// Default: false
  /// </summary>
  bool DisableCommandLineArgsPassthrough = false;

  /// <summary>
  /// Whether to disable the CEF sandbox.
  /// Only applicable on macOS; ignored on other platforms.
  /// Disabling the sandbox may be required for certain integrations or debugging.
  /// Default: true
  /// </summary>
  bool DisableSandbox = true;

  /// <summary>
  /// Additional command line arguments to be passed to CEF.
  /// Each entry maps a switch name to its value (e.g., {"remote-allow-origins", "*"}).
  /// These arguments allow fine-grained control over CEF behavior.
  /// </summary>
  TMap<FString, FString> CommandLineArgs = //
    {
      { TEXT("remote-allow-origins"), TEXT("*") },
    };
};
