//
//  Copyright © 2025 SHEEN TECH LAB. All Rights Reserved.
//
//! @file CefSettings.h
//! @brief Declares the UCefSettings class.
#pragma once

#pragma region <Engine Headers>
// Core/Public/
#include <Containers/UnrealString.h>
// CoreUObject/Public/
#include <UObject/ObjectMacros.h>
// DeveloperSettings/Public/
#include <Engine/DeveloperSettings.h>
#pragma endregion

#pragma region <Project Public Headers>
#include <CefViewTypes.h>
#pragma endregion

#pragma region "Generated Header"
#include "CefSettings.generated.h"
#pragma endregion

/// <summary>
/// Represents the log severity for CEF (Chromium Embedded Framework) logging output.
/// </summary>
/// <remarks>
/// This enumeration controls the verbosity of log messages generated by CEF. Adjusting the log level can help with
/// debugging, diagnostics, or suppressing output in production environments.
/// </remarks>
UENUM(BlueprintType)
enum class ECefLogLevel : uint8
{
  /// <summary>
  /// Default logging (currently INFO logging). This is the standard log level used if no other is specified.
  /// </summary>
  Default,

  /// <summary>
  /// Verbose logging. Includes detailed diagnostic information useful for development and troubleshooting.
  /// </summary>
  Verbose,

  /// <summary>
  /// DEBUG logging. Provides information intended for debugging purposes.
  /// </summary>
  Debug,

  /// <summary>
  /// INFO logging. General informational messages that highlight the progress of the application.
  /// </summary>
  Info,

  /// <summary>
  /// WARNING logging. Indicates potentially harmful situations or recoverable issues.
  /// </summary>
  Warning,

  /// <summary>
  /// ERROR logging. Indicates error events that might still allow the application to continue running.
  /// </summary>
  Error,

  /// <summary>
  /// FATAL logging. Indicates very severe error events that will presumably lead the application to abort.
  /// </summary>
  Fatal,

  /// <summary>
  /// Disable logging to file for all messages, and to stderr for messages with severity less than FATAL.
  /// Use this to suppress most log output.
  /// </summary>
  Disable = 99
};

/// <summary>
/// Represents the settings for CEF context initialization and configuration.
/// </summary>
/// <remarks>
/// UCefSettings allows you to customize the behavior of the embedded Chromium browser in your Unreal Engine project.
/// These settings control aspects such as resource mapping, localization, logging, debugging, and browser
/// interoperability. Changes to these settings should be made before any CEF browser instances are created.
/// </remarks>
/// <example>
/// Example usage:
/// <code>
/// UCefSettings* CefSettings = GetMutableDefault<UCefSettings>();
/// CefSettings->UserAgent = TEXT("MyCustomUserAgent/1.0");
/// </code>
/// </example>
UCLASS(BlueprintType, Config = "Engine", DefaultConfig)
class UCEFVIEW_API UCefSettings : public UDeveloperSettings
{
  GENERATED_BODY()

#pragma region Properties
public:
  /// <summary>
  /// The name of the bridge object injected into all browser frames.
  /// This object enables communication between JavaScript running in web content and native C++ code.
  /// </summary>
  /// <remarks>
  /// The bridge object is accessible in JavaScript as a property of the window object (e.g.,
  /// <c>window.bridgeObject</c>). Use this to expose native functions or data to your web UI.
  /// </remarks>
  UPROPERTY(                   //
    Config,                    //
    EditAnywhere,              //
    Category = "Interoperation" //
  )
  FName BridgeObjectName = TEXT("UCefViewBridge");

  /// <summary>
  /// The name of the built-in custom URI scheme used by the CEF context.
  /// </summary>
  /// <remarks>
  /// This scheme is used for internal resource mapping and communication between the browser and the engine.
  /// </remarks>
  UPROPERTY(                   //
    Config,                    //
    EditAnywhere,              //
    Category = "Interoperation" //
  )
  FName BuiltinSchemeName = TEXT("UCefView");

  /// <summary>
  /// The user agent string sent by the browser to web servers.
  /// </summary>
  /// <remarks>
  /// If left empty, the default Chromium user agent will be used. You can override this to identify your application or
  /// enable/disable specific web features.
  /// </remarks>
  UPROPERTY(                   //
    Config,                    //
    EditAnywhere,              //
    Category = "Interoperation" //
  )
  FString UserAgent;

  /// <summary>
  /// Archive file resource mappings for serving web content from .zip files.
  /// Only zip format is supported. Each mapping associates a virtual URL with a zip archive.
  /// </summary>
  /// <remarks>
  /// The file path must be relative to the Game directory. This allows you to package web assets efficiently.
  /// </remarks>
  UPROPERTY(                      //
    Config,                       //
    EditAnywhere,                 //
    Category = "Resource Mapping" //
  )
  TArray<FArchiveFileResourceMapping> ArchiveFileResourceMapping;

  /// <summary>
  /// Local folder resource mappings for serving web content from directories on disk.
  /// </summary>
  /// <remarks>
  /// The folder path must be relative to the Game Content directory. Use this to expose static assets (HTML, JS, CSS,
  /// etc.) to your CEF browser instances.
  /// </remarks>
  UPROPERTY(                      //
    Config,                       //
    EditAnywhere,                 //
    Category = "Resource Mapping" //
  )
  TArray<FLocalFolderResourceMapping> LocalFolderResourceMapping;

  /// <summary>
  /// The background color used for browser rendering.
  /// </summary>
  /// <remarks>
  /// This color is used as the default background for web content. Adjust it to match your application's theme.
  /// </remarks>
  UPROPERTY(                //
    Config,                 //
    EditAnywhere,           //
    Category = "Appearance" //
  )
  FColor BackgroundColor = FColor::White;

  /// <summary>
  /// The locale to use for browser UI and web content.
  /// </summary>
  /// <remarks>
  /// If empty, the default locale "en-US" is used. On Linux, this value is ignored and locale is determined by
  /// environment variables. You can also set the locale using the "lang" command-line switch.
  /// </remarks>
  UPROPERTY(                //
    Config,                 //
    EditAnywhere,           //
    Category = "Appearance" //
  )
  FString Locale;

  /// <summary>
  /// List of accepted languages for HTTP requests, used in the "Accept-Language" header.
  /// </summary>
  /// <remarks>
  /// Provide a comma-delimited, ordered list of language codes (e.g., "en-US,fr,es").
  /// This helps web servers deliver localized content.
  /// </remarks>
  UPROPERTY(                //
    Config,                 //
    EditAnywhere,           //
    Category = "Appearance" //
  )
  TArray<FString> AcceptLanguageList;

  /// <summary>
  /// Whether to persist session cookies across browser restarts.
  /// </summary>
  /// <remarks>
  /// If true, session cookies will be saved and restored. If false, they will be cleared when the browser is closed.
  /// </remarks>
  UPROPERTY(             //
    Config,              //
    EditAnywhere,        //
    Category = "Storage" //
  )
  bool PersistSessionCookies = true;

  /// <summary>
  /// Whether to persist user preferences (such as autofill data, settings, etc.).
  /// </summary>
  /// <remarks>
  /// If true, user preferences will be saved and restored between sessions.
  /// </remarks>
  UPROPERTY(             //
    Config,              //
    EditAnywhere,        //
    Category = "Storage" //
  )
  bool PersistUserPreferences = true;

  /// <summary>
  /// The log level for CEF diagnostic output.
  /// </summary>
  /// <remarks>
  /// Adjust this to control the verbosity of CEF logs. Higher verbosity can help with debugging but may impact
  /// performance.
  /// </remarks>
  UPROPERTY(                //
    Config,                 //
    EditAnywhere,           //
    Category = "Diagnostic" //
  )
  ECefLogLevel LogLevel = ECefLogLevel::Default;

  /// <summary>
  /// The port number for remote debugging with Chrome/Edge Dev Tools.
  /// </summary>
  /// <remarks>
  /// If set to a non-zero value, you can connect to the browser for debugging using Chrome or Edge at
  /// "localhost:[port]". Useful for inspecting and debugging web content at runtime.
  /// </remarks>
  UPROPERTY(                                                                  //
    Config,                                                                   //
    EditAnywhere,                                                             //
    Category = "Diagnostic",                                                  //
    meta = (ClampMin = "0", ClampMax = "65535", UIMin = "0", UIMax = "65535") //
  )
  int32 RemoteDebuggingPort = 0;

  /// <summary>
  /// Whether to disable passing the application command line arguments to CEF.
  /// </summary>
  /// <remarks>
  /// Disabling this can help prevent conflicts or unintended behavior caused by command line switches.
  /// </remarks>
  UPROPERTY(          //
    Config,           //
    EditAnywhere,     //
    Category = "Misc" //
  )
  bool DisableCommandLineArgsPassthrough = false;

  /// <summary>
  /// Whether to disable the Chromium sandbox. (Only applicable on macOS platform.)
  /// </summary>
  /// <remarks>
  /// Disabling the sandbox may be required for certain debugging or integration scenarios, but can reduce security.
  /// </remarks>
  UPROPERTY(          //
    Config,           //
    EditAnywhere,     //
    Category = "Misc" //
  )
  bool DisableSandbox = true;

  /// <summary>
  /// Additional command line arguments to be passed to CEF.
  /// </summary>
  /// <remarks>
  /// Use this to enable or configure advanced CEF features. Each entry maps a switch name to its value.
  /// For example: { "remote-allow-origins", "*" }
  /// </remarks>
  UPROPERTY(          //
    Config,           //
    EditAnywhere,     //
    Category = "Misc" //
  )
  TMap<FString, FString> CommandLineArgs = //
    {
      { TEXT("remote-allow-origins"), TEXT("*") },
    };
#pragma endregion

#if WITH_EDITOR
  /// <summary>
  /// Called after a property is changed in the editor.
  /// </summary>
  /// <param name="InPropertyChangedEvent">The property change event data.</param>
  /// <remarks>
  /// Override this method to handle property changes and perform validation or updates in the editor.
  /// </remarks>
  void PostEditChangeProperty(struct FPropertyChangedEvent& InPropertyChangedEvent) override;
#endif
};
